services:
  backend:
    container_name: backend
    build: ./backend
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
    networks:
      - fullstack
    restart: always

  postgres:
    image: postgres:latest
    container_name: postgres
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - fullstack

volumes:
  database_postgres:

networks:
  fullstack:
    driver: bridge